Scrum 46 - Created Audit trail page
allaboutmike/dsd-team-wombat pull request #39
Opened 2024-04-02 21:05 UTC by Srasulova

2024-04-03 14:39 UTC, joshuaow91 commented on wombat-admin/src/components/audit_trail.tsx
this can be mapped over as well, kind of like this


            <tbody className="divide-y divide-zinc-200 bg-white">
                {auditData.map((item, index) => (
                    <tr key={index} className="divide-x divide-zinc-200">
                        <td className="whitespace-nowrap p-4 text-sm font-medium text-zinc-800">{item.id}</td>
                        <td className="whitespace-nowrap p-4 text-sm text-zinc-500">{item.name}</td>
                      etc.
                    </tr>
                ))}
            </tbody>

2024-04-03 17:37 UTC, allaboutmike requested changes

2024-04-03 17:37 UTC, allaboutmike commented on wombat-admin/src/components/audit_trail.tsx
+1 to this. @Srasulova please update this file to use a map rather than repeating rows manually.

2024-04-05 17:59 UTC, Srasulova commented
requested changes are addressed.

2024-04-05 17:59 UTC, allaboutmike approved these changes
Fantastic. Great work.

2024-04-05 18:00 UTC, merged