Live on Firebase
allaboutmike/dsd-team-wombat pull request #80
Opened 2024-04-16 04:30 UTC by kenneth-blanton

2024-04-16 04:31 UTC, kenneth-blanton reviewed
Currently not done with get and pull requests but all of the info from firebase hosting is in here.

Live @ https://teamwombatadmin1.web.app/

2024-04-16 12:48 UTC, joshuaow91 commented
might want to link up with @Srasulova she's also been working on the GET and PUT requests for the admin dashboard

2024-04-18 04:25 UTC, allaboutmike requested changes
Overall I think we are ok, but a couple of things:

- do we need the .firebase files? These are generated. I'm not familiar with fire base, but if we don't need them on the repo let's remove / ignore them. 
- can we please clean out commented out source? If there is a need to add it back in we can put that in a Jira ticket.

2024-04-18 04:25 UTC, allaboutmike commented on wombat-admin/src/app/models/models.tsx
> +// type requestState = "AUTOMATED" | "MANUAL_OVERRIDE_REQUESTED" | "MANUAL_OVERRIDE_ACTIONED" | "MANUAL_OVERRIDE_TIMEOUT"
If these are not needed please remove them.

2024-04-18 04:25 UTC, allaboutmike commented on wombat-admin/src/app/page.tsx
> +  useEffect(() => {
Can we put this in a hook?

2024-04-18 04:25 UTC, allaboutmike commented on wombat-admin/src/app/page.tsx
> +  }, []);
Needs the setIncomingDeniedRequests as a dependency.

2024-04-18 04:25 UTC, allaboutmike commented on wombat-admin/src/app/page.tsx
> +  //const users = useDataFetcher('http://localhost:4040/users');
Nit please remove commented out code.

2024-04-19 00:19 UTC, joshuaow91 commented on wombat-admin/src/app/page.tsx
> +    const reqsBody = { state: 'MANUAL_OVERRIDE_ACTIONED', approvalStatus: "DENIED", date: request.date };
if this is the approve request hook it should have an approvalStatus of "APPROVED"

2024-04-19 02:03 UTC, FarhanDS-92 approved these changes
LGTM!!

2024-04-19 18:08 UTC, allaboutmike approved these changes
Approving to unblock.

2024-04-19 19:32 UTC, merged